# Generated by Django 5.1.15 on 2026-08-01 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftlog',
            name='employees',
            field=models.ManyToManyField(blank=True, help_text='The crew that actually worked this shift.', related_name='deep_clean_shifts', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='shiftlog',
            name='workers',
            field=models.ManyToManyField(blank=True, help_text='System-account staff on this shift (rare -- most crew are Employees below).', related_name='deep_clean_shifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ToolboxTalk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('topic', models.CharField(help_text="e.g. 'Wet floors & chemical handling'", max_length=200)),
                ('content', models.TextField(help_text='Hazards discussed, controls, PPE required.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conducted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toolbox_talks', to='projects.deepcleanproject')),
            ],
            options={
                'ordering': ['-work_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ToolboxTalkAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='toolbox_signatures/')),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='toolbox_talk_attendances', to='employees.employee')),
                ('toolbox_talk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='projects.toolboxtalk')),
            ],
            options={
                'ordering': ['employee__first_name', 'employee__last_name'],
                'constraints': [models.UniqueConstraint(fields=('toolbox_talk', 'employee'), name='uniq_toolboxtalk_employee')],
            },
        ),
    ]
