# Generated by Django 5.1.15 on 2026-08-01 06:17

import apps.documents.models
import apps.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_shiftlog_employees_alter_shiftlog_workers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deepcleanproject',
            name='station',
        ),
        migrations.AddField(
            model_name='deepcleanproject',
            name='location',
            field=models.CharField(blank=True, default='', help_text="e.g. 'Auburn Station', a client site address, etc.", max_length=200),
        ),
        migrations.AddField(
            model_name='toolboxtalk',
            name='attachment',
            field=models.FileField(blank=True, help_text='The toolbox talk paper/form, if you have one -- attendees can view it before signing.', null=True, upload_to='toolbox_talks/%Y/%m/', validators=[apps.documents.models.validate_file_extension, apps.documents.models.validate_file_size]),
        ),
        migrations.AddField(
            model_name='toolboxtalkattendee',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='toolboxtalkattendee',
            name='sign_token',
            field=models.CharField(default=apps.projects.models._generate_token, editable=False, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='toolboxtalk',
            name='content',
            field=models.TextField(blank=True, help_text='Hazards discussed, controls, PPE required.'),
        ),
    ]
