# Generated by Django 5.1.15 on 2026-08-11 08:30

import django.db.models.deletion
from django.db import migrations, models


def backfill_team_from_shift_logs(apps, schema_editor):
    """New M2M starts empty -- seed it from who's actually worked a shift
    on each project so far, so existing projects aren't blank on day one."""
    DeepCleanProject = apps.get_model("projects", "DeepCleanProject")
    for project in DeepCleanProject.objects.prefetch_related("shift_logs__employees"):
        employee_ids = {
            employee.pk
            for shift_log in project.shift_logs.all()
            for employee in shift_log.employees.all()
        }
        if employee_ids:
            project.team.set(employee_ids)


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_kiosk_pin_hash'),
        ('projects', '0003_remove_deepcleanproject_station_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deepcleanproject',
            name='team',
            field=models.ManyToManyField(blank=True, help_text='Employees working on this project -- who a toolbox talk sent to "this project\'s team" reaches.', related_name='deep_clean_projects', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='toolboxtalk',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toolbox_talks', to='projects.deepcleanproject'),
        ),
        migrations.RunPython(backfill_team_from_shift_logs, migrations.RunPython.noop),
    ]
