# Generated by Django 5.1.15 on 2026-08-11 17:08

import apps.documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_deepcleanproject_team_alter_toolboxtalk_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolboxtalk',
            name='attachment',
            field=models.FileField(blank=True, help_text='The toolbox talk paper/form, if you have one -- attendees can view it before signing.', null=True, upload_to='toolbox_talks/%Y/%m/', validators=[apps.documents.models.validate_file_extension, apps.documents.models.validate_file_size, apps.documents.models.validate_file_content]),
        ),
    ]
