# Generated by Django 5.1.15 on 2026-08-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Administrator'), ('wh_supervisor', 'Warehouse Supervisor'), ('station_supervisor', 'Station Supervisor'), ('deepclean_supervisor', 'Deep Clean Supervisor'), ('wh_staff', 'Warehouse Staff'), ('station_staff', 'Station Cleaning Staff')], max_length=32),
        ),
    ]
