# Generated by Django 5.1.15 on 2026-08-01 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCapabilityOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capability', models.CharField(max_length=64)),
                ('granted', models.BooleanField(help_text='Checked = grant this capability. Unchecked = revoke it, even if the role normally has it.')),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capability_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['capability'],
                'constraints': [models.UniqueConstraint(fields=('user', 'capability'), name='uniq_user_capability_override')],
            },
        ),
    ]
