# Generated by Django 5.1.15 on 2026-08-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usercapabilityoverride'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestRateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('scope', models.CharField(max_length=32)),
                ('window_start', models.DateTimeField()),
                ('count', models.PositiveIntegerField(default=1)),
            ],
            options={
                'indexes': [models.Index(fields=['window_start'], name='accounts_re_window__3e58f0_idx')],
                'constraints': [models.UniqueConstraint(fields=('ip_address', 'scope', 'window_start'), name='uniq_rate_limit_window')],
            },
        ),
    ]
