# Generated by Django 5.1.15 on 2026-08-12 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
        ('employees', '0003_employee_kiosk_pin_hash'),
        ('notifications', '0004_alter_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcementrecipient',
            options={'ordering': ['employee__first_name', 'employee__last_name', 'user__username']},
        ),
        migrations.RemoveConstraint(
            model_name='announcementrecipient',
            name='uniq_announcement_recipient',
        ),
        migrations.AddField(
            model_name='announcementrecipient',
            name='email_sent',
            field=models.BooleanField(default=False, help_text='Set for no-login employees, emailed directly.'),
        ),
        migrations.AddField(
            model_name='announcementrecipient',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcement_receipts', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='announcementrecipient',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcement_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='announcementrecipient',
            constraint=models.UniqueConstraint(fields=('announcement', 'user'), name='uniq_announcement_recipient_user'),
        ),
        migrations.AddConstraint(
            model_name='announcementrecipient',
            constraint=models.UniqueConstraint(fields=('announcement', 'employee'), name='uniq_announcement_recipient_employee'),
        ),
    ]
