# Generated by Django 5.1.15 on 2026-07-31 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('serial_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('qr_code_data', models.CharField(blank=True, db_index=True, max_length=128, unique=True)),
                ('qr_code_image', models.ImageField(blank=True, upload_to='equipment_qr/')),
                ('status', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('in_maintenance', 'In Maintenance'), ('lost', 'Lost'), ('written_off', 'Written Off')], default='available', max_length=20)),
                ('maintenance_interval_days', models.PositiveIntegerField(blank=True, null=True)),
                ('last_maintenance_at', models.DateField(blank=True, null=True)),
                ('next_maintenance_due', models.DateField(blank=True, db_index=True, null=True)),
                ('test_interval_days', models.PositiveIntegerField(default=365)),
                ('last_test_date', models.DateField(blank=True, null=True)),
                ('next_test_due', models.DateField(blank=True, db_index=True, null=True)),
                ('last_test_result', models.CharField(choices=[('untested', 'Untested'), ('pass', 'Pass'), ('fail', 'Fail')], default='untested', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_equipment', to=settings.AUTH_USER_MODEL)),
                ('current_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='warehouses.station')),
                ('current_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='warehouses.warehouse')),
                ('last_tested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['asset_id'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('assigned', 'Assigned'), ('released', 'Released'), ('maintenance_start', 'Maintenance Started'), ('maintenance_end', 'Maintenance Completed'), ('test_recorded', 'Safety Test Recorded'), ('lost', 'Marked Lost'), ('written_off', 'Written Off')], max_length=24)),
                ('override_used', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='equipment.equipment')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='warehouses.station')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['status'], name='equipment_e_status_fb8540_idx'),
        ),
    ]
