# Generated by Django 5.1.15 on 2026-08-11 17:08

import apps.documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/%Y/%m/', validators=[apps.documents.models.validate_file_extension, apps.documents.models.validate_file_size, apps.documents.models.validate_file_content]),
        ),
    ]
