# Generated by Django 5.1.15 on 2026-08-01 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_remove_deepcleanproject_station_and_more'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HazardReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('hazard', 'Hazard / unsafe condition'), ('near_miss', 'Near miss'), ('incident', 'Incident (injury or damage)')], default='hazard', max_length=16)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location_detail', models.CharField(blank=True, help_text="e.g. 'Platform 2, near the lift'", max_length=200)),
                ('immediate_action_taken', models.TextField(blank=True)),
                ('injury_involved', models.BooleanField(default=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='hazard_reports/%Y/%m/')),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('corrective_action', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hazard_reports', to='projects.deepcleanproject')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hazard_reports_filed', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hazard_reports', to='warehouses.station')),
            ],
            options={
                'ordering': ['-reported_at'],
                'indexes': [models.Index(fields=['status'], name='safety_haza_status_db32c4_idx'), models.Index(fields=['severity'], name='safety_haza_severit_28f666_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('project__isnull', True), ('station__isnull', False)), models.Q(('project__isnull', False), ('station__isnull', True)), _connector='OR'), name='hazard_exactly_one_site')],
            },
        ),
    ]
