# Generated by Django 5.1.15 on 2026-07-31 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(db_index=True, max_length=32, unique=True)),
                ('make_model', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('in_maintenance', 'In Maintenance'), ('written_off', 'Written Off')], default='available', max_length=20)),
                ('service_due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('insurance_expiry', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_vehicles', to=settings.AUTH_USER_MODEL)),
                ('current_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='warehouses.station')),
            ],
            options={
                'ordering': ['registration'],
            },
        ),
        migrations.CreateModel(
            name='VehicleCostLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_type', models.CharField(choices=[('fuel', 'Fuel'), ('toll', 'Toll'), ('repair', 'Repair'), ('other', 'Other')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('incurred_at', models.DateField()),
                ('comment', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(blank=True, help_text='Where the vehicle was assigned at the time of the cost.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='warehouses.station')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_logs', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-incurred_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('assigned', 'Assigned'), ('released', 'Released'), ('maintenance_start', 'Maintenance Started'), ('maintenance_end', 'Maintenance Completed'), ('written_off', 'Written Off')], max_length=24)),
                ('override_used', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='warehouses.station')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['status'], name='vehicles_ve_status_f71f77_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclecostlog',
            index=models.Index(fields=['vehicle', 'incurred_at'], name='vehicles_ve_vehicle_34edc6_idx'),
        ),
    ]
