# Generated by Django 5.1.15 on 2026-07-31 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='current_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='projects.deepcleanproject'),
        ),
        migrations.AddField(
            model_name='vehiclecostlog',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Deep clean project the vehicle was assigned to at the time of the cost.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.deepcleanproject'),
        ),
        migrations.AddField(
            model_name='vehiclelog',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.deepcleanproject'),
        ),
    ]
