# Generated by Django 5.1.15 on 2026-08-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_current_project_vehiclecostlog_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='current_station',
        ),
        migrations.RemoveField(
            model_name='vehiclecostlog',
            name='station',
        ),
        migrations.RemoveField(
            model_name='vehiclelog',
            name='station',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='current_location',
            field=models.CharField(blank=True, choices=[('deep_clean', 'Deep Clean'), ('car_park', 'Car Park'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='vehiclecostlog',
            name='location',
            field=models.CharField(blank=True, choices=[('deep_clean', 'Deep Clean'), ('car_park', 'Car Park'), ('other', 'Other')], help_text='Where the vehicle was assigned at the time of the cost.', max_length=20),
        ),
        migrations.AddField(
            model_name='vehiclelog',
            name='location',
            field=models.CharField(blank=True, choices=[('deep_clean', 'Deep Clean'), ('car_park', 'Car Park'), ('other', 'Other')], max_length=20),
        ),
    ]
