# Generated by Django 5.1.15 on 2026-07-31 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('stock_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='stock_requests.stockrequest'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='type',
            field=models.CharField(choices=[('stock_in', 'Stock In'), ('stock_out', 'Stock Out'), ('transfer_out', 'Transfer Out'), ('transfer_in', 'Transfer In'), ('adjustment', 'Adjustment'), ('return', 'Return'), ('damaged', 'Damaged'), ('lost', 'Lost'), ('expired', 'Expired'), ('reversal', 'Reversal'), ('station_usage', 'Station Usage')], max_length=20),
        ),
    ]
