# Generated by Django 5.1.15 on 2026-07-31 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventorytransaction_request_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stocklevel',
            name='uniq_stock_level_slot',
        ),
    ]
