# Generated by Django 5.1.15 on 2026-07-31 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
        ('inventory', '0003_remove_stocklevel_uniq_stock_level_slot'),
        ('projects', '0001_initial'),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='projects.deepcleanproject'),
        ),
        migrations.AddField(
            model_name='stocklevel',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_levels', to='projects.deepcleanproject'),
        ),
        migrations.AddIndex(
            model_name='stocklevel',
            index=models.Index(fields=['product', 'project'], name='inventory_s_product_fc1f77_idx'),
        ),
        migrations.AddConstraint(
            model_name='stocklevel',
            constraint=models.UniqueConstraint(fields=('product', 'warehouse', 'station', 'project', 'batch'), name='uniq_stock_level_slot'),
        ),
    ]
