# Generated by Django 5.1.15 on 2026-07-31 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventorytransaction_project_stocklevel_project_and_more'),
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='purchasing.purchaseorder'),
        ),
    ]
