# Generated by Django 5.1.15 on 2026-08-01 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventorytransaction_purchase_order'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocktake',
            options={'ordering': ['-started_at']},
        ),
        migrations.AddField(
            model_name='stocktake',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stocktakes', to='warehouses.station'),
        ),
        migrations.AlterField(
            model_name='stocktake',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stocktakes', to='warehouses.warehouse'),
        ),
        migrations.AddConstraint(
            model_name='stocktake',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('station__isnull', True), ('warehouse__isnull', False)), models.Q(('station__isnull', False), ('warehouse__isnull', True)), _connector='OR'), name='stocktake_exactly_one_site'),
        ),
    ]
