# Generated by Django 5.1.15 on 2026-08-04 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
        ('inventory', '0006_alter_stocktake_options_stocktake_station_and_more'),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStockThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reorder_point', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_thresholds', to='catalogue.product')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_thresholds', to='warehouses.station')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_thresholds', to='warehouses.warehouse')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('station__isnull', True), ('warehouse__isnull', False)), models.Q(('station__isnull', False), ('warehouse__isnull', True)), _connector='OR'), name='threshold_exactly_one_site'), models.UniqueConstraint(fields=('product', 'warehouse'), name='uniq_threshold_product_warehouse'), models.UniqueConstraint(fields=('product', 'station'), name='uniq_threshold_product_station')],
            },
        ),
    ]
