# Generated by Django 5.1.15 on 2026-08-19 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
        ('inventory', '0007_productstockthreshold'),
        ('projects', '0005_alter_toolboxtalk_attachment'),
        ('vehicles', '0003_remove_vehicle_current_station_and_more'),
        ('warehouses', '0002_station_nfc_token'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productstockthreshold',
            name='threshold_exactly_one_site',
        ),
        migrations.RemoveConstraint(
            model_name='stocklevel',
            name='uniq_stock_level_slot',
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='productstockthreshold',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_thresholds', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='stocklevel',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_levels', to='vehicles.vehicle'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='type',
            field=models.CharField(choices=[('stock_in', 'Stock In'), ('stock_out', 'Stock Out'), ('transfer_out', 'Transfer Out'), ('transfer_in', 'Transfer In'), ('adjustment', 'Adjustment'), ('return', 'Return'), ('damaged', 'Damaged'), ('lost', 'Lost'), ('expired', 'Expired'), ('reversal', 'Reversal'), ('station_usage', 'Station Usage'), ('vehicle_usage', 'Vehicle Usage')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='stocklevel',
            index=models.Index(fields=['product', 'vehicle'], name='inventory_s_product_ad8f85_idx'),
        ),
        migrations.AddConstraint(
            model_name='productstockthreshold',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('station__isnull', True), ('vehicle__isnull', True), ('warehouse__isnull', False)), models.Q(('station__isnull', False), ('vehicle__isnull', True), ('warehouse__isnull', True)), models.Q(('station__isnull', True), ('vehicle__isnull', False), ('warehouse__isnull', True)), _connector='OR'), name='threshold_exactly_one_site'),
        ),
        migrations.AddConstraint(
            model_name='productstockthreshold',
            constraint=models.UniqueConstraint(fields=('product', 'vehicle'), name='uniq_threshold_product_vehicle'),
        ),
        migrations.AddConstraint(
            model_name='stocklevel',
            constraint=models.UniqueConstraint(fields=('product', 'warehouse', 'station', 'vehicle', 'project', 'batch'), name='uniq_stock_level_slot'),
        ),
    ]
