# Generated by Django 5.1.15 on 2026-07-31 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('partially_fulfilled', 'Partially Fulfilled'), ('fulfilled', 'Fulfilled')], default='pending', max_length=24)),
                ('rejection_reason', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_requests', to='warehouses.station')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_requests', to='warehouses.warehouse')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='StockRequestLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity_dispatched', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogue.product')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='stock_requests.stockrequest')),
            ],
        ),
        migrations.AddIndex(
            model_name='stockrequest',
            index=models.Index(fields=['status', 'warehouse'], name='stock_reque_status_572506_idx'),
        ),
        migrations.AddIndex(
            model_name='stockrequest',
            index=models.Index(fields=['status', 'station'], name='stock_reque_status_c46a2d_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockrequestline',
            constraint=models.UniqueConstraint(fields=('request', 'product'), name='uniq_stock_request_line_product'),
        ),
    ]
