# Generated by Django 5.1.15 on 2026-08-04 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_employee_user'),
        ('warehouses', '0002_station_nfc_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutySheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. 6am-2pm Platform', max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_sheets', to='warehouses.station')),
            ],
            options={
                'ordering': ['station_id', 'order', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ClockEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in_at', models.DateTimeField(auto_now_add=True)),
                ('clock_out_at', models.DateTimeField(blank=True, null=True)),
                ('clock_in_method', models.CharField(choices=[('web', 'Web'), ('nfc', 'NFC tag')], default='web', max_length=8)),
                ('clock_out_method', models.CharField(blank=True, choices=[('web', 'Web'), ('nfc', 'NFC tag')], max_length=8)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clock_events', to='employees.employee')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clock_events', to='warehouses.station')),
                ('duty_sheet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clock_events', to='attendance.dutysheet')),
            ],
            options={
                'ordering': ['-clock_in_at'],
            },
        ),
        migrations.CreateModel(
            name='DutySheetTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duty_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='attendance.dutysheet')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text="e.g. why it couldn't be completed")),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employees.employee')),
                ('completed_during_clock_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_tasks', to='attendance.clockevent')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='attendance.dutysheettask')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddConstraint(
            model_name='dutysheet',
            constraint=models.UniqueConstraint(fields=('station', 'name'), name='uniq_duty_sheet_name'),
        ),
        migrations.AddConstraint(
            model_name='clockevent',
            constraint=models.UniqueConstraint(condition=models.Q(('clock_out_at__isnull', True)), fields=('employee',), name='uniq_open_clock_event_per_employee'),
        ),
        migrations.AddConstraint(
            model_name='taskcompletion',
            constraint=models.UniqueConstraint(fields=('task', 'date'), name='uniq_task_completion_per_date'),
        ),
    ]
