# Generated by Django 5.1.15 on 2026-08-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_dutysheetassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcompletion',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='task_completions/%Y/%m/'),
        ),
    ]
