# Generated by Django 5.1.15 on 2026-08-01 04:15

import apps.employees.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('position', models.CharField(blank=True, help_text='e.g. Station Cleaner, Team Leader', max_length=100)),
                ('date_started', models.DateField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('address', models.TextField(blank=True)),
                ('riw_number', models.CharField(blank=True, max_length=64, verbose_name='RIW number')),
                ('riw_expiry_date', models.DateField(blank=True, null=True, verbose_name='RIW card expiry')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=32)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True, help_text='Internal notes -- not visible to the employee.')),
                ('is_active', models.BooleanField(default=True)),
                ('invite_token', models.CharField(default=apps.employees.models._generate_invite_token, editable=False, max_length=64, unique=True)),
                ('invited_at', models.DateTimeField(blank=True, null=True)),
                ('profile_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
    ]
