# Generated by Django 5.1.15 on 2026-08-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='kiosk_pin_hash',
            field=models.CharField(blank=True, editable=False, max_length=128),
        ),
    ]
