# Generated by Django 5.1.15 on 2026-08-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('low_stock', 'Low stock'), ('expiry', 'Expiring stock'), ('maintenance_due', 'Maintenance due'), ('vehicle_compliance', 'Vehicle compliance'), ('request_outstanding', 'Outstanding request'), ('po_status', 'Purchase order'), ('stocktake_overdue', 'Stock count overdue')], max_length=24),
        ),
    ]
