# Generated by Django 5.1.15 on 2026-08-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('low_stock', 'Low stock'), ('expiry', 'Expiring stock'), ('maintenance_due', 'Maintenance due'), ('vehicle_compliance', 'Vehicle compliance'), ('request_outstanding', 'Outstanding request'), ('po_status', 'Purchase order'), ('stocktake_overdue', 'Stock count overdue'), ('hazard_reported', 'Hazard/incident reported')], max_length=24),
        ),
    ]
